[WIP ]Draft of proof bot script using ape
nucypher/train45 pull request #1
Opened 2024-02-05 18:34 UTC by vzotova

2024-02-12 12:47 UTC, manumonti requested changes
Looks good! just some typos:

2024-02-12 12:47 UTC, manumonti commented on .pre-commit-config.yaml
> +  - repo: https://github.com/psf/black
We can address this in the following PR, but maybe, for consistency, we can use the same that in nucypher/nucypher: 

https://github.com/nucypher/nucypher/blob/main/.pre-commit-config.yaml

- `Darker` instead of black and isort.
- `Ruff` instead of flake8.

2024-02-12 12:47 UTC, manumonti commented on README.md
> +ape run proof_bot --fx-root-tunnel 0x720754c84f0b1737801bf63c950914E0C1d4aCa2 --graphql-endpoint https://api.studio.thegraph.com/query/24143/polygonchildmumbai/version/latest --proof-generator https:
Just a reminder that this subgraph URL is for the development API, so the subgraph is automatically archived when it is not queried by 30 days.

A solution for using this on mainnet could be to upload the subgraph to [Alchemy's subgraph](https://subgraphs.alchemy.com/), which doesn't have this limitation. LMK if this works for you so I can address that.

2024-02-12 12:47 UTC, manumonti commented on scripts/proof_bot.py
> +        logger.info("Transaction was processed")
```suggestion
        logger.info("Transaction already processed")
```
WDYT? less confusing in my opinion.

2024-02-12 12:47 UTC, manumonti commented on scripts/proof_bot.py
> +    Queries GraphQL endpoint to retreive all new `MessageSent` events
```suggestion
    Queries GraphQL endpoint to retrieve all new `MessageSent` events
```

2024-02-12 14:48 UTC, vzotova commented on .pre-commit-config.yaml
> +  - repo: https://github.com/psf/black
✔️

2024-02-12 14:51 UTC, vzotova commented on README.md
> +ape run proof_bot --fx-root-tunnel 0x720754c84f0b1737801bf63c950914E0C1d4aCa2 --graphql-endpoint https://api.studio.thegraph.com/query/24143/polygonchildmumbai/version/latest --proof-generator https:
I trust you completely on that, I guess it would be good to have such subgraph for mainnet

2024-02-12 15:32 UTC, manumonti approved these changes
LGTM! 🙌

2024-02-14 20:36 UTC, KPrasch approved these changes
🚂

2024-02-14 20:36 UTC, merged

2024-02-15 11:06 UTC, cygnusv commented on README.md
> +Stateless bot monitors GraphQL endpoint for new events `MessageSent` that occurs on Polygon network. And then transfers proof to Ethereum root contract.
```suggestion
Stateless bot monitors GraphQL endpoint for new events `MessageSent` that occurs on Polygon network, and then transfers proof to Ethereum root contract.
```

2024-02-15 11:07 UTC, cygnusv commented
LGTM, just needs clarification that the `--network` flag is for the transacting network (in this case, Ethereum Mainnet or Goerli)